[default.variables]
font = "Maple Mono NF CN"
ui_font = "Maple Mono NF CN"
font_size = "12"
font_size_small = "8"
font_size_medium = "12"
font_size_large = "25"
font_size_xlarge = "55"
wallpaper = "~/Pictures/wallpaper/wall1.jpg"
calculator_cmd = ""
launcher_cmd = ""
gtk_theme = ""
gtk_icon_theme = ""
gtk_cursor_theme = ""
launcher_cmd = ""
clipboard_cmd = ""
gtk_theme = "AweSome"
gtk_icon_theme = "Tela-nord-dark"
gtk_cursor_theme = "volantes_cursors"
download_dependices = true
download_dependencies = false
terminal = "footclient"
class_arg = "--app-id"
filemanager_cmd = "lf"
processmanager_cmd = "btm"
terminal_cmd = "tmux new-session -A -s main"
processmanager = "processmanager"
filemanager = "filemanager"
terminal_gui = "terminal"
